### ISSUE TITLE
Can't install PPA

### ISSUE THREAD

**Issue by MoreThanLuck** [regolith-linux/speed-ricer#1]
Hey Ken! This is great. I was going to try and install and config polybar to my existing Regolith setup, but wasn't able to add the PPA. I got an error for no release file, which I think is from my Ubuntu version being unsupported, correct?

I'm running 19.04. Do I need to go up to 19.10 for this to work?

**Comment by kgilmer** [comment]
Hi @MoreThanLuck you should be just fine with 18.04, 18.10, or 19.04.  I just tested with 18.10 to be sure and had no problems: 

```
$ sudo add-apt-repository -y ppa:kgilmer/speed-ricer
...
$ sudo apt install polybar
```

Let me know if you get it working or not.

**Comment by MoreThanLuck** [comment]
Hmm, that's strange. No dice for me. Here's what I get:
`$ sudo add-apt-repository -y ppa:kgilmer/speed-ricer
[sudo] password for aelius:
Hit:1 http://us.archive.ubuntu.com/ubuntu disco InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu disco-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu disco-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu disco-security InRelease
Hit:5 http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu disco InRelease
Hit:6 http://ppa.launchpad.net/kgilmer/regolith-stable/ubuntu disco InRelease
Hit:7 http://ppa.launchpad.net/kgilmer/regolith-unstable/ubuntu disco InRelease
Hit:8 http://ppa.launchpad.net/kgilmer/speed-ricer/ubuntu disco InRelease
Hit:9 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu disco InRelease
Ign:10 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu disco InRelease
Err:11 http://ppa.launchpad.net/transmissionbt/ppa/ubuntu disco Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/transmissionbt/ppa/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by MoreThanLuck** [comment]
Dang. I was totally just misreading an error message. My bad! Think I've got it now.
