### ISSUE TITLE
Update i3-gaps-wm to 4.18.2

### ISSUE THREAD

**Issue by moritzheiber** [regolith-linux/speed-ricer#13]
Currently, [that's 4.18.1](https://github.com/Airblader/i3/releases). Needed to possibly tackle https://github.com/regolith-linux/regolith-desktop/issues/415

**Comment by aendeavor** [comment]
Would be awesome to see this happening. Any help required?

**Comment by moritzheiber** [comment]
Sure, submit a PR if you have the time. I haven’t been able to get around to it yet, it’s not because I didn’t want to 😉

**Comment by aendeavor** [comment]
@moritzheiber I would happily do that, but since this is my fist time doing something like this, I have no idea what to do and where to start. **But I would really like to learn it!** Could you help?

**Comment by aendeavor** [comment]
Alright, I will look into it.

Awesome to hear that 4.18.2 is being built!

**Comment by aendeavor** [comment]
@kgilmer Did you start a build for Ubuntu 20.04 (focal) too? I just had a look at the repo and there is still version 4.17 for focal, only for regolith is there a 4.18.

**Comment by aendeavor** [comment]
Alright @kgilmer. I just got `4.18.2` on focal. Very happy! I think this issue can be closed then.
