### ISSUE TITLE
Rename unclutter-xfices to regolith-unclutter-xfixes to avoid unclutter-startup dependency

### ISSUE THREAD

**Issue by moritzheiber** [regolith-linux/speed-ricer#14]
The regular `unclutter-xfixes` package in the Ubuntu package repositories depends on a package called `unclutter-startup` which installs a service that starts `unclutter` during the start of any X session. Unfortunately, it conflicts with our handling of `unclutter`, in particular, it basically makes it impossible to set `unclutter` options through `Xresources`. `regolith-desktop` already conflicts with `unclutter-startup`, but since it's installing configuration files to `/etc` a mere removal isn't going to remove its startup instructions (leaving us with the same issue).

The solution is to have `regolith-desktop` depend on a package named differently than the default Ubuntu package and explicitly avoid the `unclutter-startup` dependency.

**Comment by kgilmer** [comment]
Thank you for providing detailed explanation of the issue @moritzheiber , it made for easy fixing all these monthslater. The Regolith variant of `unclutter-xfixes` had been staged in the speed-ricer 'monorepo' which doesn't work well with gbp.  i have moved into a new dedicated package and prefixed `regolith-` to the package name to break free of the conflict with the ubuntu version, and have added packaging metadata such that the regolith variant conflicts with the ubuntu variant, so hopefully this should resolve the issue for all users from 1.5.

Here is the new package: https://github.com/regolith-linux/regolith-unclutter-xfixes

There  will be an update to `regolith-builder` to add the new package to the 1.5 model and an update to regolith desktop to depend on the new package.
