### ISSUE TITLE
Unable to locate package polybar

### ISSUE THREAD

**Issue by JonathanCasters** [regolith-linux/speed-ricer#8]
I first installed the PPA:
`sudo add-apt-repository ppa:kgilmer/speed-ricer`
but when I tried to install the polybar package by using this command:
`sudo apt install polybar`
I got this error message:
`E: Unable to locate package polybar`
Is there an issue with the package?

_Using Ubuntu 19.10 with regolith linux._

**Comment by kgilmer** [comment]
Hi @JonathanCasters :) I just built a 19.10 version of the package.  Can you `sudo apt update` and try again?

**Comment by JonathanCasters** [comment]
Problem solved!
Many Thanks!
