### ISSUE TITLE
Package rename from "compton" to "picom"

### ISSUE THREAD

**Issue by tiritto** [regolith-linux/speed-ricer#9]
I believe that it might be appropriate to rename "compton" package to "picom". Such change would make it clear right away that the provided package is a maintained fork of Compton rather than old Compton. On top of avoiding general versioning confusion, I believe it will also somehow help out Picom maintainers by making people more aware of Picom presence as de facto Compton successor.

**Comment by kgilmer** [comment]
Hi @tiritto, I'm being lazy and waiting for a new version that actually has something to offer other than the name change.

**Comment by moritzheiber** [comment]
Closing this as a duplicate of https://github.com/regolith-linux/regolith-desktop/issues/419
